// CatÃ¡logo completo enriquecido de Animais, Cogumelos, Podas e Mondas
// Todas as imagens apontam para fotografias locais fiÃ¡veis em /images/...

export const DEFAULT_ANIMALS = [
  // --- AVES ---
  {
    id: "animal_galinhas",
    name: "Galinhas Poedeiras",
    scientific_name: "Gallus gallus domesticus",
    emoji: "ðŸ”",
    color: "#c2410c",
    image_url: "./images/animals/galinha.jpg",
    category: "Aves",
    difficulty: "FÃ¡cil",
    space_needed: "0.5 mÂ² no galinheiro por ave e 2 a 4 mÂ² em parque exterior vedado.",
    daily_effort: "Baixo",
    where_to_keep: "Galinheiro seco e ventilado, com poleiros altos, ninhos confortÃ¡veis e proteÃ§Ã£o contra raposas e doninhas.",
    how_to_keep: "Recolha diÃ¡ria de ovos, Ã¡gua limpa sempre fresca e reposiÃ§Ã£o periÃ³dica de palha ou serradura seca na cama.",
    care: "DesparasitaÃ§Ã£o regular externa e interna, controlo de piolho vermelho e arejamento sem correntes de ar frias.",
    feeding: "RaÃ§Ã£o de postura equilibrada, milho partido, sobras de hortaliÃ§a e casca de ostra moÃ­da para cÃ¡lcio.",
    feed_items: "Milho partido, raÃ§Ã£o de postura, folhas de couve, casca de ostra triturada, restos de horta",
    treatment: "VacinaÃ§Ã£o em jovens, suplementos vitamÃ­nicos na muda da pena e acesso a terra ou cinza para banhos de pÃ³.",
    what_they_do: "Produzem ovos frescos todos os dias, fornecem estrume rico em azoto (galinhaÃ§a) para composto e limpam restos de culturas.",
    special_info: "Uma galinha saudÃ¡vel pÃµe em mÃ©dia 250 a 300 ovos por ano em condiÃ§Ãµes ideais de luz e alimentaÃ§Ã£o."
  },
  {
    id: "animal_galo",
    name: "Galo Reprodutor",
    scientific_name: "Gallus gallus domesticus",
    emoji: "ðŸ“",
    color: "#ea580c",
    image_url: "./images/animals/galo.jpg",
    category: "Aves",
    difficulty: "FÃ¡cil",
    space_needed: "Mesmo espaÃ§o do galinheiro; 1 galo para cada 8 a 12 galinhas.",
    daily_effort: "Baixo",
    where_to_keep: "Junto do bando de galinhas no galinheiro principal com poleiro dominante.",
    how_to_keep: "Evitar manter mais de um galo no mesmo espaÃ§o para evitar disputas territoriais agressivas.",
    care: "Aparar esporÃµes se ficarem demasiado compridos para nÃ£o ferir as galinhas durante a cobriÃ§Ã£o.",
    feeding: "Mesma alimentaÃ§Ã£o das galinhas, com reforÃ§o de sementes e cereais energÃ©ticos.",
    feed_items: "Mistura de cereais (trigo, cevada e milho), verduras frescas e suplemento mineral",
    treatment: "InspeÃ§Ã£o de esporÃµes e desparasitaÃ§Ã£o idÃªntica Ã  do galinheiro.",
    what_they_do: "Protege e alerta o bando contra predadores, fertiliza os ovos para incubaÃ§Ã£o e mantÃ©m a harmonia hierÃ¡rquica do bando.",
    special_info: "O canto do galo serve para marcar territÃ³rio e tranquilizar as fÃªmeas logo ao amanhecer."
  },
  {
    id: "animal_patos",
    name: "Patos DomÃ©sticos",
    scientific_name: "Anas platyrhynchos domesticus",
    emoji: "ðŸ¦†",
    color: "#0284c7",
    image_url: "./images/animals/pato.jpg",
    category: "Aves",
    difficulty: "FÃ¡cil",
    space_needed: "Parque amplo com tanque, bacia grande ou charco de Ã¡gua rasa.",
    daily_effort: "MÃ©dio",
    where_to_keep: "Abrigo tÃ©rreo bem fechado Ã  noite e terreno com relva e Ã¡gua durante o dia.",
    how_to_keep: "ObrigatÃ³rio ter Ã¡gua funda o suficiente para mergulharem o bico e limparem as narinas e olhos.",
    care: "Excelente resistÃªncia natural a doenÃ§as; necessitam de chÃ£o sempre seco no ninho para dormir.",
    feeding: "Cereais (trigo e milho moÃ­do), forragem verde, e pequenos invertebrados da horta.",
    feed_items: "Milho triturado, trigo em grÃ£o, verduras frescas, caracÃ³is e lesmas",
    treatment: "Acesso a Ã¡gua limpa permanente para prevenÃ§Ã£o de infeÃ§Ãµes oculares.",
    what_they_do: "Excelente controlo biolÃ³gico de pragas (comem caracÃ³is e lesmas vorazmente sem estragar as raÃ­zes como as galinhas).",
    special_info: "Os ovos de pata sÃ£o mais ricos em gorduras e proteÃ­nas, sendo muito apreciados para pastelaria e pÃ£o-de-lÃ³ tradicional."
  },
  {
    id: "animal_gansos",
    name: "Gansos de Guarda",
    scientific_name: "Anser anser domesticus",
    emoji: "ðŸª¿",
    color: "#059669",
    image_url: "./images/animals/ganso.jpg",
    category: "Aves",
    difficulty: "FÃ¡cil",
    space_needed: "Parque exterior com boa cobertura vegetal e acesso a ponto de Ã¡gua.",
    daily_effort: "Baixo",
    where_to_keep: "Cercado amplo com erva abundante; abrigo simples coberto para a noite.",
    how_to_keep: "Gostam de viver em casais ou pequenos grupos; territoriais e muito vigilantes.",
    care: "Aves rÃºsticas que raramente adoecem. Apenas exigem pasto limpo e Ã¡gua fresca.",
    feeding: "Essencialmente herbÃ­voros: pastam relva fresca, trevo, dente-de-leÃ£o e cereais suplementares no inverno.",
    feed_items: "Pasto verde fresco, trigo, aveia, milho no inverno",
    treatment: "DesparasitaÃ§Ã£o anual e proteÃ§Ã£o contra humidade excessiva nos ninhos.",
    what_they_do: "SÃ£o excelentes cÃ£es de guarda naturais da quinta (fazem alarme sonoro a qualquer intruso) e cortadores de relva ecolÃ³gicos.",
    special_info: "Os romanos usavam gansos sagrados para guardar o CapitÃ³lio devido ao seu sono leve e alarme ruidoso."
  },
  {
    id: "animal_perus",
    name: "Perus de Campo",
    scientific_name: "Meleagris gallopavo",
    emoji: "ðŸ¦ƒ",
    color: "#854d0e",
    image_url: "./images/animals/peru.jpg",
    category: "Aves",
    difficulty: "MÃ©dia",
    space_needed: "Ãrea aberta de pelo menos 6 mÂ² por ave e poleiros robustos.",
    daily_effort: "MÃ©dio",
    where_to_keep: "PavilhÃ£o seco, ventilado e sem correntes de ar frias.",
    how_to_keep: "Comedouros suspensos limpos; solo seco forrado a palha grossa.",
    care: "Muito sensÃ­veis Ã  humidade nas primeiras 8 semanas de vida; manter longe de galinhas para evitar a 'cabeÃ§a negra' (histomonÃ­ase).",
    feeding: "RaÃ§Ã£o de alto teor proteico nos jovens, grÃ£os de milho, aveia e verduras na fase adulta.",
    feed_items: "RaÃ§Ã£o de engorda, milho partido, aveia, luzerna e couves",
    treatment: "Controlo de coccidiose em pintos e desparasitaÃ§Ã£o periÃ³dica.",
    what_they_do: "ProduÃ§Ã£o de carne magra de alta qualidade e limpeza de lagartas e gafanhotos em pomares e soutos.",
    special_info: "TÃªm audiÃ§Ã£o apurada e vocalizam em coro a qualquer barulho sÃºbito."
  },
  {
    id: "animal_codornizes",
    name: "Codornizes",
    scientific_name: "Coturnix japonica",
    emoji: "ðŸ¦",
    color: "#a16207",
    image_url: "./images/animals/codorniz.jpg",
    category: "Aves",
    difficulty: "FÃ¡cil",
    space_needed: "Gaiolas ou mÃ³dulos com 0.15 a 0.2 mÂ² por ave (ideais para quintas com pouco espaÃ§o).",
    daily_effort: "Baixo",
    where_to_keep: "MÃ³dulos de rede elevados protegidos da chuva, ratos e correntes de ar.",
    how_to_keep: "Piso ligeiramente inclinado para rolamento suave dos ovos e recolha fÃ¡cil.",
    care: "Manter temperatura amena e luminosidade de 14h/dia para postura constante.",
    feeding: "RaÃ§Ã£o prÃ³pria de codorniz poedeira rica em proteÃ­na (20-22%) e cÃ¡lcio fino.",
    feed_items: "RaÃ§Ã£o especÃ­fica para codorniz, sementes finas de painÃ§o, verduras picadas",
    treatment: "Higiene rigorosa do tabuleiro de dejetos a cada 2 dias.",
    what_they_do: "Iniciam a postura logo Ã s 6 semanas de vida; ovos densos em nutrientes, ferro e vitaminas.",
    special_info: "Cinco ovos de codorniz equivalem em peso a um ovo de galinha, mas tÃªm significativamente mais fÃ³sforo e vitaminas B."
  },
  {
    id: "animal_pintadas",
    name: "Galinhas-d'angola (Pintadas)",
    scientific_name: "Numida meleagris",
    emoji: "ðŸª¶",
    color: "#475569",
    image_url: "./images/animals/pintada.jpg",
    category: "Aves",
    difficulty: "MÃ©dia",
    space_needed: "Terreno amplo e arborizado; gostam de liberdade de movimentos.",
    daily_effort: "Baixo",
    where_to_keep: "Empoleiram-se em Ã¡rvores altas ou em telheiros bem elevados Ã  noite.",
    how_to_keep: "SÃ£o aves semi-selvagens que preferem forragear sozinhas pelos olivais e campos.",
    care: "RÃºsticas e imunes Ã  maioria das maleitas normais de galinheiro.",
    feeding: "Milho, sementes silvestres e enorme quantidade de carraÃ§as, formigas e insetos.",
    feed_items: "Milho, trigo, insetos apanhados no campo, verduras",
    treatment: "Apenas abrigo seco em dias de tempestade forte no inverno.",
    what_they_do: "Inimigas nÃºmero um das carraÃ§as no campo; caÃ§am cobras pequenas e avisam com gritos estridentes a presenÃ§a de intrusos.",
    special_info: "Em zonas rurais de Portugal sÃ£o tradiÃ§Ã£o como 'sentinelas' de propriedades contra rÃ©pteis e parasitas."
  },

  // --- COELHOS ---
  {
    id: "animal_coelhos",
    name: "Coelhos da Quinta",
    scientific_name: "Oryctolagus cuniculus",
    emoji: "ðŸ°",
    color: "#78716c",
    image_url: "./images/animals/coelho.jpg",
    category: "Coelhos",
    difficulty: "FÃ¡cil",
    space_needed: "Coelheiras individuais ou parques de chÃ£o de 1 a 2 mÂ² por exemplar.",
    daily_effort: "Baixo",
    where_to_keep: "Coelheira abrigada do calor direto no verÃ£o, da humidade e de predadores.",
    how_to_keep: "Feno de prado sempre disponÃ­vel no comedouro para digestÃ£o e desgaste dos dentes incisivos.",
    care: "Limpeza regular de estrumeiras e bebedouros de pipeta automÃ¡ticos com Ã¡gua fresca.",
    feeding: "80% feno de qualidade, 15% raÃ§Ã£o granulada e 5% verduras fibrosas (folhas de cenoura, chicÃ³ria, salsa).",
    feed_items: "Feno de montanha, raÃ§Ã£o em pellets, folhas de cenoura, raminhos de oliveira ou macieira",
    treatment: "Vacina anual contra Mixomatose e DoenÃ§a HemorrÃ¡gica Viral (DHV).",
    what_they_do: "Produzem o famoso 'estrume frio' de coelho, o melhor adubo biolÃ³gico direto para hortaliÃ§as e flores (nÃ£o queima as raÃ­zes).",
    special_info: "O estrume de coelho nÃ£o precisa de meses de fermentaÃ§Ã£o: pode ser misturado imediatamente na terra dos canteiros."
  },
  {
    id: "animal_coelho_flandres",
    name: "Coelho Gigante de Flandres",
    scientific_name: "Oryctolagus cuniculus domesticus",
    emoji: "ðŸ‡",
    color: "#57534e",
    image_url: "./images/animals/coelho_flandres.jpg",
    category: "Coelhos",
    difficulty: "MÃ©dia",
    space_needed: "Coelheira extragrande (mÃ­nimo 2 a 3 mÂ²) com piso suave para proteger as patas traseiras.",
    daily_effort: "MÃ©dio",
    where_to_keep: "Piso plano e forrado a palha grossa para evitar pododermatite (chagas nas patas).",
    how_to_keep: "Animal muito dÃ³cil e calmo; tolera muito bem a interaÃ§Ã£o humana e crianÃ§as.",
    care: "AtenÃ§Ã£o ao excesso de peso e ao calor no pico do verÃ£o (muito sensÃ­veis a golpes de calor).",
    feeding: "Grandes quantidades de feno fresco, forragem verde e raÃ§Ã£o rica em fibras.",
    feed_items: "Feno de prado em abundÃ¢ncia, alfafa, cenoura com ramas, raÃ§Ã£o de coelho",
    treatment: "VacinaÃ§Ã£o anual e controlo de peso.",
    what_they_do: "Excelente animal para pequenas exploraÃ§Ãµes familiares de carne ou quinta pedagÃ³gica pelo porte impressionante.",
    special_info: "Podem atingir entre 7 a 10 kg de peso e mais de 80 cm de comprimento total."
  },
  {
    id: "animal_coelho_anao",
    name: "Coelho AnÃ£o",
    scientific_name: "Oryctolagus cuniculus",
    emoji: "ðŸ‡",
    color: "#a8a29e",
    image_url: "./images/animals/coelho_anao.jpg",
    category: "Coelhos",
    difficulty: "FÃ¡cil",
    space_needed: "Gaiola espaÃ§osa de pelo menos 100 x 50 cm ou cercadinho de interior/jardim.",
    daily_effort: "Baixo",
    where_to_keep: "Local calmo, protegido de ventos fortes e calor excessivo.",
    how_to_keep: "Enriquecimento com tÃºneis e blocos de madeira natural nÃ£o tratada para roer.",
    care: "Escovagem semanal na muda do pelo para evitar bolas de pelo no estÃ´mago.",
    feeding: "Feno de capim de alta qualidade, pequenas porÃ§Ãµes de verduras frescas e pellets sem cereais.",
    feed_items: "Feno aromÃ¡tico de montanha, folhas de dente-de-leÃ£o, salsa, hortelÃ£, pellets prÃ³prios",
    treatment: "VacinaÃ§Ã£o contra DHV-1 e DHV-2.",
    what_they_do: "Ideal para quintas familiares pedagÃ³gicas, lazer e companhia dÃ³cil.",
    special_info: "Um coelho anÃ£o adulto pesa habitualmente entre 1 a 1.5 kg."
  },

  // --- CAPRINOS ---
  {
    id: "animal_cabras_leite",
    name: "Cabras Serranas e Leiteiras",
    scientific_name: "Capra hircus",
    emoji: "ðŸ",
    color: "#b45309",
    image_url: "./images/animals/cabra.jpg",
    category: "Caprinos",
    difficulty: "MÃ©dia",
    space_needed: "Cercado exterior com rede forte (mÃ­nimo 1.30 m) e estÃ¡bulo seco de 2 mÂ² por cabeÃ§a.",
    daily_effort: "MÃ©dio",
    where_to_keep: "Aprisco bem arejado com solo seco e cama de palha limpa; odeiam pisos hÃºmidos e chuva.",
    how_to_keep: "Cercas robustas porque sÃ£o curiosas e sobem a qualquer sÃ­tio; colocar troncos ou pedras para treparem.",
    care: "Aparar cascos trimestralmente e manter desparasitaÃ§Ã£o interna e externa em dia.",
    feeding: "Arbustos, tojos, giestas, silvas, feno de luzerna e cevada ou milho na ordenha.",
    feed_items: "Mato mediterrÃ¢nico, feno de luzerna, palha de cevada, milho triturado, pedra de sal com minerais",
    treatment: "Vacina contra enterotoxÃ©mia e desparasitante pÃ³s-parto.",
    what_they_do: "Produzem leite de excelente qualidade para queijos tradicionais e limpam mato com extrema eficÃ¡cia contra incÃªndios.",
    special_info: "As cabras conseguem digerir plantas espinhosas e silvas que outros animais recusam comer."
  },
  {
    id: "animal_cabras_anas",
    name: "Cabras AnÃ£s",
    scientific_name: "Capra hircus",
    emoji: "ðŸ",
    color: "#d97706",
    image_url: "./images/animals/cabra_ana.jpg",
    category: "Caprinos",
    difficulty: "FÃ¡cil",
    space_needed: "Pequeno cercado de 50 a 100 mÂ² para 2 a 3 animais e abrigo coberto.",
    daily_effort: "Baixo",
    where_to_keep: "Casinha de madeira elevada do chÃ£o com rampa de acesso e cercadinho seguro.",
    how_to_keep: "Devem ser mantidas em pares (sÃ£o animais muito gregÃ¡rios que entram em depressÃ£o sozinhos).",
    care: "Corte de cascos regular e abrigo 100% seco.",
    feeding: "Feno de boa qualidade, folhas de oliveira, ramos de Ã¡rvores de fruto e suplemento de cereais.",
    feed_items: "Feno de prado, raminhos de poda de oliveira, cenouras, maÃ§Ã£s em pedaÃ§os, sal mineral",
    treatment: "DesparasitaÃ§Ã£o semestral.",
    what_they_do: "Excelentes para limpeza de quintas e pomares pequenos, animais de companhia excecionais e atraÃ§Ã£o pedagÃ³gica.",
    special_info: "Muito brincalhonas e afeitas ao dono, reconhecem o nome e adoram carinho."
  },

  // --- OVINOS ---
  {
    id: "animal_ovelhas",
    name: "Ovelhas de Pasto (Churra)",
    scientific_name: "Ovis aries",
    emoji: "ðŸ‘",
    color: "#65a30d",
    image_url: "./images/animals/ovelha.jpg",
    category: "Ovinos",
    difficulty: "FÃ¡cil",
    space_needed: "Pastagem natural de 500 a 1000 mÂ² por cabeÃ§a e aprisco para as noites frias.",
    daily_effort: "MÃ©dio",
    where_to_keep: "Aprisco seco com manjedouras limpas e acesso diÃ¡rio a pasto cercado.",
    how_to_keep: "Maneio em rebanho rotacional para permitir a regeneraÃ§Ã£o da erva dos cercados.",
    care: "Tosquia anual na primavera (maio/junho), corte de unhas e desparasitaÃ§Ã£o contra tÃ©nias e fascÃ­ola.",
    feeding: "Erva de pasto, feno de trevo e luzerna no outono/inverno e cereais na fase final de gestaÃ§Ã£o.",
    feed_items: "Erva fresca de prado, feno de azevÃ©m, farelo de trigo, cevada e bloco de sal mineral",
    treatment: "VacinaÃ§Ã£o contra basculho (enterotoxÃ©mia) e banhos desparasitantes contra sarna.",
    what_they_do: "Produzem lÃ£ natural, leite para queijo de ovelha curado, mantÃªm os prados podados e fertilizam o solo uniformemente.",
    special_info: "A saliva das ovelhas contÃ©m enzimas que estimulam o crescimento radicular das gramÃ­neas quando pastam."
  },
  {
    id: "animal_carneiro",
    name: "Carneiro Reprodutor",
    scientific_name: "Ovis aries",
    emoji: "ðŸ",
    color: "#4d7c0f",
    image_url: "./images/animals/carneiro.jpg",
    category: "Ovinos",
    difficulty: "MÃ©dia",
    space_needed: "Mesma Ã¡rea do rebanho; proporÃ§Ã£o de 1 carneiro para cada 25 a 35 ovelhas.",
    daily_effort: "MÃ©dio",
    where_to_keep: "Junto do rebanho na Ã©poca de cobriÃ§Ã£o e em cercado prÃ³prio se for necessÃ¡rio separar.",
    how_to_keep: "Maneio calmo e seguro; atenÃ§Ã£o Ã  forÃ§a dos cornos e investidas na Ã©poca de cio das fÃªmeas.",
    care: "InspeÃ§Ã£o dos cascos e verificaÃ§Ã£o periÃ³dica da condiÃ§Ã£o corporal antes da Ã©poca reprodutiva.",
    feeding: "ReforÃ§o proteico e vitamÃ­nico semanas antes da cobriÃ§Ã£o para garantir mÃ¡xima fertilidade.",
    feed_items: "Feno de primeira qualidade, grÃ£os de aveia, cevada e minerais ricos em fÃ³sforo",
    treatment: "DesparasitaÃ§Ã£o antes de juntar Ã s fÃªmeas.",
    what_they_do: "Garante a renovaÃ§Ã£o genÃ©tica e nascimentos anuais de borregos com vigor e rusticidade.",
    special_info: "Possui olfato apurado que deteta a fertilidade das ovelhas a dezenas de metros de distÃ¢ncia."
  },

  // --- SUÃNOS ---
  {
    id: "animal_porco_alentejano",
    name: "Porco Alentejano / IbÃ©rico",
    scientific_name: "Sus scrofa domesticus",
    emoji: "ðŸ–",
    color: "#a16207",
    image_url: "./images/animals/porco_alentejano.jpg",
    category: "SuÃ­nos",
    difficulty: "MÃ©dia",
    space_needed: "Parque exterior extenso de montado com azinheiras e sobreiros ou terreno cercado reforÃ§ado.",
    daily_effort: "MÃ©dio",
    where_to_keep: "Malhada ou pocilga com zona coberta para dormir e amplo parque de terra para focinhar.",
    how_to_keep: "Cerca elÃ©trica ou rede grossa rente ao chÃ£o (os porcos tÃªm enorme forÃ§a no focinho e levantam redes soltas).",
    care: "Zona de lama no verÃ£o para banhos (nÃ£o transpiram e precisam de lama para regular a temperatura e proteger a pele de parasitas).",
    feeding: "Bolotas de azinho e sobro no outono (montanheira), cereais moÃ­dos, favas, abÃ³boras e pasto verde.",
    feed_items: "Bolota, milho moÃ­do, farelo de trigo, couves, maÃ§Ã£s caÃ­das, abÃ³boras",
    treatment: "VacinaÃ§Ã£o oficial obrigatÃ³ria contra doenÃ§a de Aujeszky e desparasitaÃ§Ã£o.",
    what_they_do: "Transformam sobras vegetais em carne e enchidos da mais alta qualidade gastronÃ³mica e preparam a terra fofando o solo.",
    special_info: "A carne de porco de montanheira tem gordura infiltrada rica em Ã¡cido oleico, saudÃ¡vel como o azeite virgem."
  },
  {
    id: "animal_porco_bisaro",
    name: "Porco BÃ­saro e LeitÃµes",
    scientific_name: "Sus scrofa domesticus",
    emoji: "ðŸ–",
    color: "#c2410c",
    image_url: "./images/animals/porco_bisaro.jpg",
    category: "SuÃ­nos",
    difficulty: "MÃ©dia",
    space_needed: "Pocilga com maternidade de 8 mÂ² e parque exterior de exercÃ­cio.",
    daily_effort: "MÃ©dio",
    where_to_keep: "InstalaÃ§Ã£o com barras de proteÃ§Ã£o nos cantos da maternidade para nÃ£o esmagar os leitÃµes ao deitar.",
    how_to_keep: "Cama abundante de palha seca e limpa, renovada diariamente para os leitÃµes recÃ©m-nascidos.",
    care: "LÃ¢mpada de calor infravermelha nas duas primeiras semanas de vida dos leitÃµes.",
    feeding: "RaÃ§Ã£o de porca lactante, beterraba forrageira, castanhas no norte do paÃ­s e abÃ³boras.",
    feed_items: "Castanhas, batata cozida, abÃ³bora amarela, farinhas de cereais e forragem verde",
    treatment: "Suplemento de ferro injectÃ¡vel nos leitÃµes ao terceiro dia de vida.",
    what_they_do: "RaÃ§a autÃ³ctone portuguesa dÃ³cil de orelhas descaÃ­das, ideal para produÃ§Ã£o familiar de leitÃ£o e fumeiro regional.",
    special_info: "O porco BÃ­saro Ã© uma das raÃ§as mais antigas da PenÃ­nsula IbÃ©rica, tÃ­pica de TrÃ¡s-os-Montes e Minho."
  },

  // --- BOVINOS ---
  {
    id: "animal_vacas_leite",
    name: "Vacas Leiteiras (FrÃ­sia / Holstein)",
    scientific_name: "Bos taurus",
    emoji: "ðŸ„",
    color: "#1e293b",
    image_url: "./images/animals/vaca_leiteira.jpg",
    category: "Bovinos",
    difficulty: "DifÃ­cil",
    space_needed: "Pasto de 2000 a 4000 mÂ² por animal e estÃ¡bulo com cubÃ­culo individual confortÃ¡vel.",
    daily_effort: "Alto",
    where_to_keep: "EstÃ¡bulo com boa ventilaÃ§Ã£o, piso anti-derrapante e bebedouros de nÃ­vel constante.",
    how_to_keep: "HorÃ¡rios de ordenha rigorosos duas vezes por dia com higiene absoluta de tetinas e canecas.",
    care: "DesinfeÃ§Ã£o pÃ³s-ordenha (selagem de tetos) para prevenir mastites e corte de unhas regular.",
    feeding: "Silagem de milho, feno de azevÃ©m de primeiro corte e raÃ§Ã£o balanceada conforme a produÃ§Ã£o leiteira diÃ¡ria.",
    feed_items: "Silagem de milho, feno de azevÃ©m, luzerna em rama, farinha de soja e milho, pedra de sal mineral",
    treatment: "Desparasitantes na secagem e controlo reprodutivo por veterinÃ¡rio.",
    what_they_do: "Produzem entre 25 a 40 litros de leite fresco por dia e produzem grande volume de estrume para biogÃ¡s e adubo.",
    special_info: "Uma vaca leiteira de alta produÃ§Ã£o bebe entre 100 a 150 litros de Ã¡gua fresca diariamente."
  },
  {
    id: "animal_vacas_carne",
    name: "Vacas AutÃ³ctones (BarrosÃ£ / Maronesa)",
    scientific_name: "Bos taurus",
    emoji: "ðŸ‚",
    color: "#78350f",
    image_url: "./images/animals/vaca_barrosa.jpg",
    category: "Bovinos",
    difficulty: "MÃ©dia",
    space_needed: "Pastagens de montanha ou soutos amplos em regime semi-extensivo.",
    daily_effort: "MÃ©dio",
    where_to_keep: "Abrigo rÃºstico de pedra ou madeira para os meses rigorosos de neve e chuva.",
    how_to_keep: "Aproveitamento direto de pastagens de serra e ladeiras Ã­ngremes inacessÃ­veis a mÃ¡quinas.",
    care: "Vacas extraordinariamente rÃºsticas, de parto fÃ¡cil sem necessidade de auxÃ­lio humano.",
    feeding: "Erva de lameiro, feno de prado de montanha, palha e folhas de carvalho e castanheiro.",
    feed_items: "Pasto de lameiro, feno de montanha, farinha de milho regional na engorda",
    treatment: "Profilaxia oficial e vacinaÃ§Ãµes obrigatÃ³rias da DGAV.",
    what_they_do: "PreservaÃ§Ã£o da paisagem contra mato inflamÃ¡vel, carne com denominaÃ§Ã£o de origem protegida (DOP) de excelÃªncia.",
    special_info: "A raÃ§a BarrosÃ£ tem cornos majestosos em forma de lira e uma forÃ§a de traÃ§Ã£o histÃ³rica incomparÃ¡vel."
  },

  // --- EQUÃDEOS ---
  {
    id: "animal_burro_miranda",
    name: "Burro de Miranda (Burro MirandÃªs)",
    scientific_name: "Equus asinus",
    emoji: "ðŸ«",
    color: "#52525b",
    image_url: "./images/animals/burro.jpg",
    category: "EquÃ­deos",
    difficulty: "FÃ¡cil",
    space_needed: "Paddock ou pasto de 1000 mÂ² por animal e estrebaria seca e arejada.",
    daily_effort: "Baixo",
    where_to_keep: "Estrebaria com solo forrado a palha grossa; nÃ£o toleram humidade permanente nos cascos.",
    how_to_keep: "Escovagem frequente para limpar o pelo comprido e lanoso caracterÃ­stico da raÃ§a mirandesa.",
    care: "Aparar cascos a cada 6 a 8 semanas com ferrador experiente; nunca deixar cascos compridos demais.",
    feeding: "Dieta rica em fibra e pobre em aÃ§Ãºcares: palha de cevada, feno de prado e pouco cereal para nÃ£o causar laminite.",
    feed_items: "Palha limpa de cevada, feno seco de montanha, raminhos de amoreira e bloco mineral",
    treatment: "VacinaÃ§Ã£o anual contra tÃ©tano e gripe equina; desparasitaÃ§Ã£o oral em pasta.",
    what_they_do: "Trabalho agrÃ­cola ligeiro na horta, traÃ§Ã£o em charrua tradicional, asnoterapia e excelente companhia dÃ³cil.",
    special_info: "O Burro de Miranda Ã© uma raÃ§a autÃ³ctone portuguesa protegida, famosa pela sua docilidade extrema com crianÃ§as."
  },
  {
    id: "animal_cavalo_lusitano",
    name: "Cavalo Lusitano",
    scientific_name: "Equus caballus",
    emoji: "ðŸŽ",
    color: "#3f3f46",
    image_url: "./images/animals/cavalo.jpg",
    category: "EquÃ­deos",
    difficulty: "DifÃ­cil",
    space_needed: "Boxe individual de 3.5 x 3.5 m e picadeiro ou campo cercado para exercÃ­cio diÃ¡rio.",
    daily_effort: "Alto",
    where_to_keep: "Cocheira limpa diariamente, com boa ventilaÃ§Ã£o e sem poeiras irritantes para as vias respiratÃ³rias.",
    how_to_keep: "ExercÃ­cio fÃ­sico diÃ¡rio indispensÃ¡vel para a saÃºde articular, muscular e mental do cavalo.",
    care: "Limpeza diÃ¡ria de cascos antes e depois do trabalho, ferragem mensal e escovagem de crina e cauda.",
    feeding: "Feno de excelente qualidade distribuÃ­do 3 vezes por dia, aveia ou raÃ§Ã£o equilibrada e Ã¡gua limpa e fresca.",
    feed_items: "Feno de prado de primeiro corte, aveia laminada, cenouras, farelo molhado e sal",
    treatment: "VacinaÃ§Ã£o contra tÃ©tano, gripe equina, desparasitaÃ§Ã£o programada e controlo dentÃ¡rio anual.",
    what_they_do: "O cavalo de sela mais antigo do mundo, extraordinÃ¡rio para maneio de gado no campo, equitaÃ§Ã£o e trabalho de traÃ§Ã£o.",
    special_info: "O Puro Sangue Lusitano Ã© mundialmente aclamado pela sua coragem, nobreza de carÃ¡ter e lealdade ao cavaleiro."
  },
  {
    id: "animal_garrano",
    name: "PÃ³nei / Cavalo Garrano",
    scientific_name: "Equus caballus",
    emoji: "ðŸ´",
    color: "#713f12",
    image_url: "./images/animals/garrano.jpg",
    category: "EquÃ­deos",
    difficulty: "MÃ©dia",
    space_needed: "Pasto de montanha ou cercado natural com abrigo rÃºstico.",
    daily_effort: "MÃ©dio",
    where_to_keep: "Pasto amplo de encosta; sÃ£o muito Ã¡geis a subir e descer terrenos acidentados do GerÃªs.",
    how_to_keep: "Vivem bem em liberdade parcial ou no quintal familiar com espaÃ§o aberto.",
    care: "Cascos riquÃ­ssimos e resistentes que raramente precisam de ferraduras.",
    feeding: "AlimentaÃ§Ã£o simples Ã  base de pasto natural, feno e tojos jovens.",
    feed_items: "Erva de montanha, feno seco, maÃ§Ã£s e palha",
    treatment: "DesparasitaÃ§Ã£o regular e chipagem obrigatÃ³ria.",
    what_they_do: "Pequenos trabalhos de traÃ§Ã£o na horta, sela para jovens e preservaÃ§Ã£o ecolÃ³gica dos baldios florestais.",
    special_info: "O Garrano sobreviveu desde o PaleolÃ­tico no norte de Portugal e Ã© resistente aos predadores selvagens como o lobo."
  },

  // --- APICULTURA ---
  {
    id: "animal_abelhas",
    name: "Abelhas MelÃ­feras (Apis mellifera)",
    scientific_name: "Apis mellifera iberiensis",
    emoji: "ðŸ",
    color: "#ca8a04",
    image_url: "./images/animals/abelha.jpg",
    category: "Apicultura",
    difficulty: "MÃ©dia",
    space_needed: "Colmeia modelo Langstroth ou Reversible instalada a mais de 50 metros de caminhos pÃºblicos.",
    daily_effort: "Baixo",
    where_to_keep: "ApiÃ¡rio virado a nascente/sul, protegido dos ventos frios do norte e com boa exposiÃ§Ã£o solar.",
    how_to_keep: "Visitas de maneio quinzenais na primavera para evitar enxameaÃ§Ã£o e colocar alÃ§as melÃ­feras.",
    care: "Uso obrigatÃ³rio de fato completo de apicultor com mÃ¡scara e fumigador para acalmar as abelhas nas inspeÃ§Ãµes.",
    feeding: "Autossuficientes: recolhem nÃ©ctar e pÃ³len das flores num raio de 3 km. Fornecer xarope de aÃ§Ãºcar no inverno se escassear mel.",
    feed_items: "Flores da horta e pomar (alecrim, tomilho, rosmaninho, laranjeira, trevo), xarope estimulante 1:1 na prÃ©-primavera",
    treatment: "Tratamento outonal rigoroso contra o Ã¡caro Varroa destructor homologado pela DGAV.",
    what_they_do: "Polinizam mais de 75% das plantas da horta e Ã¡rvores do pomar, multiplicando a colheita de fruta, alÃ©m de produzirem mel e prÃ³polis.",
    special_info: "Para produzir 1 kg de mel puro, as abelhas de uma colmeia visitam cerca de 4 a 5 milhÃµes de flores."
  },
  {
    id: "animal_colmeia",
    name: "Colmeia e ApiÃ¡rio",
    scientific_name: "Apis mellifera",
    emoji: "ðŸ¯",
    color: "#eab308",
    image_url: "./images/animals/colmeia.jpg",
    category: "Apicultura",
    difficulty: "MÃ©dia",
    space_needed: "EspaÃ§o para 2 a 5 colmeias dispostas em linha com suporte elevado do solo a 30-40 cm.",
    daily_effort: "Baixo",
    where_to_keep: "Terreno abrigado com ponto de Ã¡gua limpa por perto para as abelhas beberem.",
    how_to_keep: "RevisÃ£o regular de quadros de criaÃ§Ã£o da rainha e colocaÃ§Ã£o de cera moldada limpa.",
    care: "PrevenÃ§Ã£o da vespa asiÃ¡tica (velutina) com armadilhas seletivas e grelhas de entrada estreitas.",
    feeding: "Pasta proteica de candi no fim do inverno para arranque forte da postura da rainha.",
    feed_items: "Candi proteico, cera de abelha pura esterilizada, Ã¡gua limpa com flutuadores",
    treatment: "DesinfeÃ§Ã£o com maÃ§arico das caixas e quadros vazios entre temporadas.",
    what_they_do: "Gera mel puro centrifugado, cera de abelha para velas e pomadas ecolÃ³gicas, prÃ³polis e pÃ³len apÃ­cola fresco.",
    special_info: "Uma colmeia saudÃ¡vel e forte alberga entre 50.000 a 80.000 abelhas operÃ¡rias no auge da primavera."
  }
];

export const DEFAULT_MUSHROOMS = [
  {
    id: "mush_tortulho",
    name: "Tortulho / Frade",
    scientific_name: "Macrolepiota procera",
    emoji: "ðŸ„",
    color: "#16a34a",
    image_url: "./images/mushrooms/tortulho.jpg",
    edibility: "ComestÃ­vel",
    common_names: "Frade, PÃºcaro, Gasalho",
    habitat: "Prados, clareiras de floresta, pinhais e montados de sobro",
    season_months: [9, 10, 11, 12],
    cap_description: "ChapÃ©u em forma de guarda-sol de grandes dimensÃµes (10 a 30 cm) com escamas castanhas sobre fundo esbranquiÃ§ado.",
    lookalikes: "Pode ser confundido com a perigosa Lepiota cristata (mas esta Ãºltima Ã© muito pequena, menos de 4 cm).",
    preparation: "Consome-se apenas o chapÃ©u (o pÃ© Ã© fibroso demais); delicioso grelhado inteiro na brasa com azeite, alho e sal grosso.",
    tips: "O anel do pÃ© Ã© mÃ³vel â€” se conseguir correr o anel pelo pÃ© acima e abaixo com facilidade, Ã© sinal clÃ¡ssico de identificaÃ§Ã£o."
  },
  {
    id: "mush_sancha",
    name: "Sancha / NÃ­scaro",
    scientific_name: "Lactarius deliciosus",
    emoji: "ðŸ„",
    color: "#16a34a",
    image_url: "./images/mushrooms/sancha.jpg",
    edibility: "ComestÃ­vel",
    common_names: "NÃ­scaro, Sancha, Pinheira",
    habitat: "Sob pinhais mansos e bravos em solos Ã¡cidos",
    season_months: [10, 11, 12, 1],
    cap_description: "ChapÃ©u alaranjado com zonas concÃªntricas avermelhadas e manchas esverdeadas com o toque e envelhecimento.",
    lookalikes: "Lactarius chrysorrheus (deita lÃ¡tex branco que se torna amarelo rÃ¡pido e Ã© picante / nÃ£o comestÃ­vel).",
    preparation: "Excelente assado na frigideira com alho e toucinho, ou estufado em arroz de cogumelos aromÃ¡tico.",
    tips: "Ao cortar o pÃ© ou as lÃ¢minas, liberta um lÃ¡tex de cor de cenoura vivo inconfundÃ­vel."
  },
  {
    id: "mush_boletus",
    name: "Boleto Edulis / Cepa",
    scientific_name: "Boletus edulis",
    emoji: "ðŸ„",
    color: "#16a34a",
    image_url: "./images/mushrooms/boletus.jpg",
    edibility: "ComestÃ­vel",
    common_names: "Porcino, Cepa, Tortulho dos carvalhos",
    habitat: "Florestas de castanheiros, carvalhais e pinhais hÃºmidos",
    season_months: [9, 10, 11],
    cap_description: "ChapÃ©u castanho-claro aveludado, pÃ© robusto e bojudo com um retÃ­culo esbranquiÃ§ado fino perto do chapÃ©u.",
    lookalikes: "Tylopilus felleus (tem sabor extremamente amargo que arruina qualquer prato) e Boletus satanas (tÃ³xico, com poros vermelhos).",
    preparation: "Um dos cogumelos mais valorizados na gastronomia mundial: fatiado em risottos, massas, salteado ou desidratado em lascas.",
    tips: "Ao contrÃ¡rio da maioria dos cogumelos com lÃ¢minas, a parte inferior do chapÃ©u tem esponja (tubos) branca que fica amarelada com a idade."
  },
  {
    id: "mush_cantarela",
    name: "Cantarela / Rapa-marotos",
    scientific_name: "Cantharellus cibarius",
    emoji: "ðŸ„",
    color: "#16a34a",
    image_url: "./images/mushrooms/cantarela.jpg",
    edibility: "ComestÃ­vel",
    common_names: "CanÃ¡rio, Rapazinhos, Chanterelle",
    habitat: "Bosques de carvalhos, castanheiros e pinhais com musgo",
    season_months: [5, 6, 9, 10, 11],
    cap_description: "Amarelo-gema a dourado brilhante, em forma de funil ou trombeta, com pregas grossas ramificadas em vez de lÃ¢minas verdadeiras.",
    lookalikes: "Omphalotus olearius (falso chanterelle das oliveiras, muito tÃ³xico â€” cresce em tufos de madeira e tem lÃ¢minas verdadeiras).",
    preparation: "Sabor delicado e frutado a alperce; salteado simples em manteiga ou azeite com salsa fresca.",
    tips: "Quase nunca Ã© atacado por larvas ou bichos devido a compostos naturais protetores."
  },
  {
    id: "mush_morchella",
    name: "Morquela / Cogumelo-de-favo",
    scientific_name: "Morchella esculenta",
    emoji: "ðŸ„",
    color: "#d97706",
    image_url: "./images/mushrooms/morchella.jpg",
    edibility: "ComestÃ­vel com precauÃ§Ã£o",
    common_names: "Morchela, Favo-de-mel, Cogumelo-da-primavera",
    habitat: "Solos calcÃ¡rios, junto a freixos, pomares de macieiras e zonas de antigas queimas",
    season_months: [3, 4, 5],
    cap_description: "ChapÃ©u oco com formato cÃ³nico e cavidades profundas irregulares parecidas com favos de abelha.",
    lookalikes: "Gyromitra esculenta (altamente tÃ³xica e perigosa, com formato que lembra um cÃ©rebro convoluto em vez de alvÃ©olos).",
    preparation: "NUNCA COMER CRU. ContÃ©m toxinas hemolÃ­ticas volÃ¡teis que se destroem totalmente com a cozedura prolongada (mÃ­nimo 20 minutos) ou apÃ³s secagem.",
    tips: "Ao abrir longitudinalmente, o cogumelo e o pÃ© devem formar uma Ãºnica cavidade oca contÃ­nua da base ao topo."
  },
  {
    id: "mush_miscaro",
    name: "MÃ­scaro-amarelo",
    scientific_name: "Tricholoma equestre",
    emoji: "ðŸ„",
    color: "#ea580c",
    image_url: "./images/mushrooms/miscaro.jpg",
    edibility: "TÃ³xico",
    common_names: "Cogumelo dos cavaleiros, MÃ­scaro da serra",
    habitat: "Pinhais em solos arenosos da Beira Alta e Litoral",
    season_months: [10, 11, 12],
    cap_description: "Amarelo-esverdeado viscoso ao centro com lÃ¢minas amarelas de enxofre vivas.",
    lookalikes: "Tradicionalmente muito colhido na Beira Alta, mas hoje proibido para venda na UE.",
    preparation: "NÃƒO CONSUMIR. O consumo repetido em doses sucessivas provoca rabdomiÃ³lise (destruiÃ§Ã£o severa do tecido muscular esquelÃ©tico e miocÃ¡rdio).",
    tips: "Embora outrora considerado comestÃ­vel tradicional, estudos toxicolÃ³gicos modernos provaram que pode ser mortal por acumulaÃ§Ã£o."
  },
  {
    id: "mush_amanita_muscaria",
    name: "Amanita Matamoscas",
    scientific_name: "Amanita muscaria",
    emoji: "ðŸ„",
    color: "#ea580c",
    image_url: "./images/mushrooms/amanita_muscaria.jpg",
    edibility: "TÃ³xico",
    common_names: "Falso tortulho, Cogumelo dos contos de fadas",
    habitat: "Sob bÃ©tulas, pinheiros e castanheiros",
    season_months: [9, 10, 11, 12],
    cap_description: "Vermelho vivo a alaranjado, coberto de verrugas piramidais brancas que se podem soltar com a chuva forte.",
    lookalikes: "Amanita caesarea (esta Ãºltima tem lÃ¢minas e pÃ© amarelos e chapÃ©u liso sem verrugas e Ã© comestÃ­vel de luxo).",
    preparation: "TÃ“XICO GRAVE. ContÃ©m Ã¡cido ibotÃ©nico e muscimol. Provoca alucinaÃ§Ãµes severas, delÃ­rios, vÃ³mitos, tremores e convulsÃµes.",
    tips: "Ã‰ o cogumelo mais famoso e ilustrado dos livros infantis, mas deve ser apreciado apenas visualmente na floresta."
  },
  {
    id: "mush_amanita_phalloides",
    name: "Amanita Cicuta Verde",
    scientific_name: "Amanita phalloides",
    emoji: "â˜ ï¸",
    color: "#dc2626",
    image_url: "./images/mushrooms/amanita_phalloides.jpg",
    edibility: "Mortal",
    common_names: "Cicuta-verde, ChapÃ©u-da-morte",
    habitat: "Carvalhais, sobreirais, castinÃ§ais e pinhais",
    season_months: [9, 10, 11],
    cap_description: "Verde-oliva a verde-amarelado pÃ¡lido com fibrilhas radiais, lÃ¢minas brancas que NUNCA escurecem e volva em saco na base do pÃ©.",
    lookalikes: "Pode ser tragicamente confundido com tortulhos jovens em botÃ£o ou com cogumelos comestÃ­veis do gÃ©nero Russula virescens.",
    preparation: "MORTAL. Uma Ãºnica amostra de 30 gramas Ã© suficiente para matar um adulto por necrose hepÃ¡tica fulminante e falÃªncia renal.",
    tips: "Apresenta 'falsa melhora clÃ­nica' apÃ³s os primeiros vÃ³mitos, o que atrasa a ida ao hospital. A volva em saco na base do pÃ© enterrado na terra Ã© a marca mortal."
  }
];

export const DEFAULT_PODAS = [
  // --- VINHA ---
  {
    id: "poda_vinha_inverno",
    name: "Videira - Poda de Inverno",
    emoji: "ðŸ‡",
    color: "#7c3aed",
    image_url: "./images/podas/vinha.jpg",
    category: "Vinha",
    when_months: [1, 2, 3],
    when_info: "Durante o repouso vegetativo de inverno profundo, antes do choro da videira (fevereiro a inÃ­cio de marÃ§o).",
    pruning_types: "Poda em seco (de produÃ§Ã£o): sistemas Royat (cordÃ£o com talÃµes) ou Guyot (vara e talÃ£o de reserva).",
    how: "Corte das varas que jÃ¡ produziram. Deixar varas com 2 a 3 gomos produtivos bem formados e eliminar varas fracas ou mal posicionadas. Manter o equilÃ­brio entre o crescimento vegetativo e a carga de uva.",
    tools: "Tesoura de poda de uma mÃ£o bem afiada, serrote pequeno para ramos velhos e soluÃ§Ã£o alcoÃ³lica para desinfeÃ§Ã£o entre cepas.",
    tips: "O corte deve ser sempre inclinado (em bisel) no sentido oposto ao gomo mais alto para evitar que a Ã¡gua da chuva e as lÃ¡grimas de seiva escorram sobre a gema fÃ©rtil.",
    difficulty: "MÃ©dia"
  },
  {
    id: "poda_vinha_verde",
    name: "Videira - Poda em Verde",
    emoji: "ðŸŒ¿",
    color: "#16a34a",
    image_url: "./images/podas/vinha_verde.jpg",
    category: "Vinha",
    when_months: [5, 6, 7],
    when_info: "Final da primavera e inÃ­cio do verÃ£o, durante o crescimento ativo dos pÃ¢mpanos e apÃ³s o vingamento das uvas.",
    pruning_types: "Desponta, esladroamento, desfolha pontual na zona dos cachos e monda de cachos.",
    how: "Eliminar rebentos ladrÃµes que brotam da madeira velha. Despontar as extremidades dos ramos longos para travar o crescimento e concentrar nutrientes nos cachos. Retirar algumas folhas velhas Ã  volta dos cachos para arejamento.",
    tools: "Tesoura de poda pequena ou desbaste manual dos rebentos tenros com os dedos.",
    tips: "Arejar os cachos previne o oÃ­dio e o mÃ­ldio, permitindo que a luz solar direta melhore a maturaÃ§Ã£o dos bagos e a concentraÃ§Ã£o de aÃ§Ãºcares.",
    difficulty: "FÃ¡cil"
  },

  // --- FRUTEIRAS DE PEPITA ---
  {
    id: "poda_macieira",
    name: "Macieira",
    emoji: "ðŸŽ",
    color: "#dc2626",
    image_url: "./images/podas/macieira.jpg",
    category: "Fruteiras de pepita",
    when_months: [1, 2],
    when_info: "Pleno inverno quando a macieira tiver perdido completamente as folhas e a seiva estiver em repouso total.",
    pruning_types: "Poda de formaÃ§Ã£o nos primeiros anos (taÃ§a ou eixo central); poda anual de frutificaÃ§Ã£o e renovaÃ§Ã£o de dardos.",
    how: "Eliminar ramos cruzados, ramos secos ou doentes e os ladrÃµes verticais que roubam vigor. Clarear o centro da Ã¡rvore para criar uma copa aberta que receba luz solar em todas as maÃ§Ã£s interiores.",
    tools: "TesourÃ£o de poda de dois braÃ§os, tesoura de poda afiada e serrote curvo para pernadas mais grossas.",
    tips: "Preservar os lambiques e dardos curtos (Ã³rgÃ£os florais onde nascem as maÃ§Ã£s). Evitar cortar pontas frutÃ­feras saudÃ¡veis sem necessidade.",
    difficulty: "FÃ¡cil"
  },
  {
    id: "poda_pereira",
    name: "Pereira (PÃªra Rocha)",
    emoji: "ðŸ",
    color: "#84cc16",
    image_url: "./images/podas/pereira.jpg",
    category: "Fruteiras de pepita",
    when_months: [1, 2],
    when_info: "Meses frios de janeiro e fevereiro antes do inchamento dos gomos florais.",
    pruning_types: "Poda de limpeza, desbaste de ramos vigorosos e manutenÃ§Ã£o da pirÃ¢mide ou taÃ§a.",
    how: "Suprimir ladrÃµes muito verticais, encurtar os ramos mistos muito compridos e selecionar os esporÃµes e bolsas com botÃµes de flor mais compactos e perto do eixo principal.",
    tools: "Tesoura de poda de corte deslizante bem afiada e desinfetada.",
    tips: "As pereiras tÃªm forte tendÃªncia para o crescimento vertical erecto. Arquear suavemente alguns ramos laterais ajuda a antecipar a produÃ§Ã£o de fruta.",
    difficulty: "FÃ¡cil"
  },
  {
    id: "poda_marmeleiro",
    name: "Marmeleiro",
    emoji: "ðŸˆ",
    color: "#eab308",
    image_url: "./images/podas/marmeleiro.jpg",
    category: "Fruteiras de pepita",
    when_months: [1, 2],
    when_info: "Durante o repouso vegetativo invernal.",
    pruning_types: "Poda ligeira de manutenÃ§Ã£o e desbaste interior.",
    how: "Eliminar ramos cruzados no interior da copa, retirar madeira seca e eliminar os rebentos que nascem no colo da raiz. O marmeleiro frutifica na extremidade dos raminhos formados no prÃ³prio ano.",
    tools: "Tesoura de poda e serrote de podar pequeno.",
    tips: "NÃ£o desponte excessivamente as pontas dos ramos exteriores, pois Ã© aÃ­ que surgirÃ£o os botÃµes florais na primavera.",
    difficulty: "FÃ¡cil"
  },

  // --- FRUTEIRAS DE CAROÃ‡O ---
  {
    id: "poda_pessegueiro",
    name: "Pessegueiro e Nectarina",
    emoji: "ðŸ‘",
    color: "#f97316",
    image_url: "./images/podas/pessegueiro.jpg",
    category: "Fruteiras de caroÃ§o",
    when_months: [2, 3],
    when_info: "Fim do inverno, quando os botÃµes de flor comeÃ§am a inchar mas antes de abrirem as pÃ©talas cor-de-rosa.",
    pruning_types: "Poda rigorosa de frutificaÃ§Ã£o anual; o pessegueiro produz apenas na madeira nova crescida no ano anterior.",
    how: "Remover ramos que jÃ¡ frutificaram e ficaram exaustos. Desbastar os ramos mistos, mantendo os ramos vigorosos com gomos triplos (dois gomos florais com um gomo de madeira ao meio). Encurtar ramos compridos em 30%.",
    tools: "Tesoura de poda muito bem afiada e mastique cicatrizante para selar cortes grossos.",
    tips: "Muito suscetÃ­vel Ã  lepra do pessegueiro e cancro bacteriano: aplicar calda bordalesa imediatamente apÃ³s a conclusÃ£o da poda.",
    difficulty: "MÃ©dia"
  },
  {
    id: "poda_cerejeira",
    name: "Cerejeira",
    emoji: "ðŸ’",
    color: "#be123c",
    image_url: "./images/podas/cerejeira.jpg",
    category: "Fruteiras de caroÃ§o",
    when_months: [8, 9],
    when_info: "Final do verÃ£o (agosto e setembro), imediatamente apÃ³s a colheita das cerejas, ou muito suavemente no inÃ­cio da floraÃ§Ã£o.",
    pruning_types: "Poda suave em verde de limpeza; NUNCA podar no inverno profundo para evitar a gomose.",
    how: "Remover ramos doentes, partidos pelo peso da colheita ou entrecruzados. Manter a copa aberta e arejada. Reduzir a altura das copas que subiram em demasia.",
    tools: "Serrote de dente fino japonÃªs e tesoura de podar afiada.",
    tips: "A cerejeira cicatriza muito mal em tempo hÃºmido e frio, segregando goma pegajosa. Podar com tempo quente e seco garante cicatrizaÃ§Ã£o instantÃ¢nea.",
    difficulty: "MÃ©dia"
  },
  {
    id: "poda_ameixeira",
    name: "Ameixeira",
    emoji: "ðŸ«",
    color: "#6b21a8",
    image_url: "./images/podas/ameixeira.jpg",
    category: "Fruteiras de caroÃ§o",
    when_months: [1, 2, 3],
    when_info: "Fim do inverno, pouco antes do inÃ­cio da brotaÃ§Ã£o vegetativa.",
    pruning_types: "Poda de arejamento de copa e rejuvenescimento de ramos velhos.",
    how: "Clarear o centro da copa retirando os ramos vigorosos verticais e encurtar ligeiramente os ramos pendentes. Conservar os buquÃªs de maio e ramos curtos com botÃµes florais.",
    tools: "Tesoura de poda de duas mÃ£os e tesoura de corte bypass.",
    tips: "As ameixeiras tendem a ter colheitas alternadas ('safra e contra-safra'). Uma poda equilibrada atenua essa alternÃ¢ncia e melhora o calibre das ameixas.",
    difficulty: "FÃ¡cil"
  },
  {
    id: "poda_damasqueiro",
    name: "Damasqueiro (Alperceiro)",
    emoji: "ðŸŠ",
    color: "#ea580c",
    image_url: "./images/podas/damasqueiro.jpg",
    category: "Fruteiras de caroÃ§o",
    when_months: [2, 3],
    when_info: "Fevereiro a inÃ­cio de marÃ§o, com botÃµes bem visÃ­veis.",
    pruning_types: "Poda de frutificaÃ§Ã£o moderada e abertura da copa em taÃ§a.",
    how: "Eliminar ramos cruzados ou sombreados no centro da Ã¡rvore. Despontar os ramos mistos fracos e manter os esporÃµes curtos de produÃ§Ã£o.",
    tools: "Tesoura afiada e pasta cicatrizante de cobre para proteÃ§Ã£o imediata das feridas.",
    tips: "Ãrvore de floraÃ§Ã£o muito precoce: proteja os rebentos abertos de geadas tardias de primavera.",
    difficulty: "MÃ©dia"
  },

  // --- CITRINOS ---
  {
    id: "poda_laranjeira",
    name: "Laranjeira",
    emoji: "ðŸŠ",
    color: "#f97316",
    image_url: "./images/podas/laranjeira.jpg",
    category: "Citrinos",
    when_months: [3, 4, 5],
    when_info: "Primavera, apÃ³s a apanha das laranjas de inverno e quando tiver passado o perigo de geadas tardias.",
    pruning_types: "Poda de limpeza, arejamento e rejuvenescimento suave.",
    how: "Remover ramos secos, partidos ou que toquem no chÃ£o. Eliminar os 'chupones' ou ladrÃµes vigorosos do interior da copa que roubam seiva. Manter a copa equilibrada em forma arredondada sem despir o tronco.",
    tools: "Tesoura de poda ergonÃ³mica e luvas grossas para proteger dos espinhos.",
    tips: "Os citrinos nÃ£o toleram podas drÃ¡sticas. Desbastar apenas o suficiente para que a luz e o ar circulem, prevenindo cochonilhas e fumagina.",
    difficulty: "FÃ¡cil"
  },
  {
    id: "poda_limoeiro",
    name: "Limoeiro 4 EstaÃ§Ãµes",
    emoji: "ðŸ‹",
    color: "#eab308",
    image_url: "./images/podas/limoeiro.jpg",
    category: "Citrinos",
    when_months: [3, 4, 5],
    when_info: "InÃ­cio da primavera (marÃ§o e abril) ou logo apÃ³s a vaga principal de limÃµes de inverno.",
    pruning_types: "Poda de desbaste interior contÃ­nuo.",
    how: "Eliminar os ladrÃµes verticais que brotam com forÃ§a no meio da Ã¡rvore sem flores. Manter a saia da Ã¡rvore a cerca de 50 cm do solo para evitar podridÃµes com a chuva e terra.",
    tools: "TesourÃ£o de podar e tesoura de uma mÃ£o desinfetada.",
    tips: "O limoeiro produz vÃ¡rias floraÃ§Ãµes por ano; evite cortar ramos carregados de botÃµes florais pequenos.",
    difficulty: "FÃ¡cil"
  },
  {
    id: "poda_clementineira",
    name: "Tangerineira e Clementina",
    emoji: "ðŸŠ",
    color: "#d97706",
    image_url: "./images/podas/clementineira.jpg",
    category: "Citrinos",
    when_months: [3, 4],
    when_info: "Logo apÃ³s a colheita dos frutos de outono/inverno.",
    pruning_types: "Poda ligeira de equilÃ­brio e desbaste central.",
    how: "Limpar o centro da copa, remover ramos dÃ©beis e encurtar ramos finos que verguem demasiado sob o peso da fruta.",
    tools: "Tesoura de poda e luvas de proteÃ§Ã£o.",
    tips: "Clementinas produzem em ramos finos e ramificados; preservar a copa frondosa mas sem emaranhados.",
    difficulty: "FÃ¡cil"
  },

  // --- OLIVEIRA ---
  {
    id: "poda_oliveira",
    name: "Oliveira - Poda de ProduÃ§Ã£o",
    emoji: "ðŸ«’",
    color: "#65a30d",
    image_url: "./images/podas/oliveira.jpg",
    category: "Oliveira",
    when_months: [2, 3, 4],
    when_info: "Logo a seguir Ã  apanha da azeitona (fevereiro e marÃ§o) atÃ© ao aparecimento dos primeiros botÃµes florais em abril.",
    pruning_types: "Poda de produÃ§Ã£o bienal em taÃ§a aberta e iluminaÃ§Ã£o do miolo.",
    how: "Remover os ramos velhos que jÃ¡ frutificaram no ano anterior e desbastar ramos verticais que sobem ao cÃ©u. Deixar a Ã¡rvore com 3 a 4 ramos mestres bem distribuÃ­dos.",
    tools: "Serrote de poda de corte em traÃ§Ã£o, tesourÃ£o telescÃ³pico e motosserra de poda ligeira para ramos grossos.",
    tips: "A sabedoria popular diz que uma oliveira bem podada deve permitir a um pÃ¡ssaro voar atravÃ©s da copa sem esbarrar nas folhas.",
    difficulty: "MÃ©dia"
  },
  {
    id: "poda_oliveira_desladroamento",
    name: "Oliveira - Desladroamento",
    emoji: "ðŸŒ³",
    color: "#4d7c0f",
    image_url: "./images/podas/oliveira_desladroamento.jpg",
    category: "Oliveira",
    when_months: [6, 7, 8],
    when_info: "VerÃ£o (junho a agosto) com tempo quente e seco.",
    pruning_types: "Desladroamento manual da base do tronco e colo da raiz.",
    how: "Cortar rente ao cepo todos os rebentos vigorosos ('ladrÃµes' ou varejÃµes) que brotam da base do tronco ou do chÃ£o e que roubam Ã¡gua e nutrientes Ã  copa produtiva.",
    tools: "Sacho afiado, podÃ£o ou tesoura de poda bem encostada Ã  casca do tronco.",
    tips: "Quanto mais cedo os ladrÃµes forem removidos no inÃ­cio do verÃ£o, menor serÃ¡ a perda de vigor para a maturaÃ§Ã£o da azeitona.",
    difficulty: "FÃ¡cil"
  },

  // --- FRUTOS SECOS E OUTRAS ---
  {
    id: "poda_amendoeira",
    name: "Amendoeira",
    emoji: "ðŸ¥œ",
    color: "#a16207",
    image_url: "./images/podas/amendoeira.jpg",
    category: "Frutos secos",
    when_months: [11, 12, 1],
    when_info: "InÃ­cio do inverno (novembro a janeiro) antes da floraÃ§Ã£o precoce tÃ­pica de fevereiro.",
    pruning_types: "Poda ligeira de manutenÃ§Ã£o e desbaste.",
    how: "Remover ramos partidos, secos e os ramos que se cruzam no interior. As amÃªndoas formam-se em ramos de 2 anos e esporÃµes persistentes que duram atÃ© 5 anos.",
    tools: "Tesoura de poda e serrote higienizado.",
    tips: "A amendoeira floresce muito cedo em Portugal; realizar a poda antes de abrir a flor para nÃ£o prejudicar a polinizaÃ§Ã£o pelas abelhas.",
    difficulty: "FÃ¡cil"
  },
  {
    id: "poda_castanheiro",
    name: "Castanheiro (Souto)",
    emoji: "ðŸŒ°",
    color: "#78350f",
    image_url: "./images/podas/castanheiro.jpg",
    category: "Frutos secos",
    when_months: [1, 2],
    when_info: "Pleno inverno com a Ã¡rvore em dormÃªncia absoluta.",
    pruning_types: "Poda de formaÃ§Ã£o nos jovens e poda sanitÃ¡ria e de clareio em soutos adultos.",
    how: "Eliminar ramos afetados por cancro do castanheiro ou ramos secos. Clarear copas densas para permitir a entrada de luz e facilitar o desenvolvimento dos ouriÃ§os.",
    tools: "Serrote de poda de cabo longo, tesoura de duas mÃ£os e pasta cicatrizante com fungicida cÃºprico.",
    tips: "Desinfetar cuidadosamente todas as lÃ¢minas entre Ã¡rvores para travar a propagaÃ§Ã£o do fungo do cancro (Cryphonectria parasitica).",
    difficulty: "MÃ©dia"
  },
  {
    id: "poda_figueira",
    name: "Figueira",
    emoji: "ðŸª´",
    color: "#15803d",
    image_url: "./images/podas/figueira.jpg",
    category: "Fruteiras de folha caduca",
    when_months: [1, 2],
    when_info: "Durante o repouso invernal apÃ³s a queda total das folhas e antes do despertar da seiva.",
    pruning_types: "Poda moderada de arejamento e limitaÃ§Ã£o de altura.",
    how: "Cortar ramos secos, ramos baixos que dificultem a passagem e ramos cruzados. Para figos lampos (primeira colheita em junho), preservar as pontas dos ramos do ano anterior onde jÃ¡ se encontram os botÃµes.",
    tools: "Serrote de poda e tesourÃ£o.",
    tips: "A madeira da figueira Ã© macia e oca no centro; nÃ£o corte rente ao tronco principal sem necessidade para evitar cavidades onde a Ã¡gua da chuva se acumule.",
    difficulty: "FÃ¡cil"
  },

  // --- PEQUENOS FRUTOS ---
  {
    id: "poda_framboesa",
    name: "Framboeseiro",
    emoji: "ðŸ“",
    color: "#e11d48",
    image_url: "./images/podas/framboesa.jpg",
    category: "Pequenos frutos",
    when_months: [1, 2, 12],
    when_info: "Inverno profundo.",
    pruning_types: "Distinguir entre variedades nÃ£o-remontantes (1 produÃ§Ã£o de verÃ£o) e remontantes (2 produÃ§Ãµes outono/verÃ£o).",
    how: "Nas nÃ£o-remontantes: cortar rente ao solo todas as varas velhas que deram fruto no verÃ£o anterior e atar as varas novas jovens ao arame. Nas remontantes: podar a ponta que deu fruta no outono ou cortar tudo rente ao solo para colheita Ãºnica abundante de fim de verÃ£o.",
    tools: "Tesoura de podar de mÃ£o pequena e luvas de proteÃ§Ã£o contra espinhos.",
    tips: "Uma boa seleÃ§Ã£o de varas (deixar cerca de 6 a 8 varas fortes por metro linear) garante frutos de grande calibre e doÃ§ura.",
    difficulty: "FÃ¡cil"
  },
  {
    id: "poda_mirtilo",
    name: "Mirtileiro",
    emoji: "ðŸ«",
    color: "#1d4ed8",
    image_url: "./images/podas/mirtilo.jpg",
    category: "Pequenos frutos",
    when_months: [1, 2],
    when_info: "Final do inverno antes do abrolhamento dos botÃµes.",
    pruning_types: "Poda de renovaÃ§Ã£o gradual e clareio da base.",
    how: "Remover os ramos com mais de 4 anos (madeira acinzentada e rugosa) cortando junto Ã  base. Deixar varas jovens de cor avermelhada ou esverdeada que produzem as melhores bagas.",
    tools: "Tesoura de poda bypass afiada.",
    tips: "O mirtilo prefere solos Ã¡cidos; apÃ³s a poda, renove a cobertura morta com casca de pinheiro e caruma.",
    difficulty: "FÃ¡cil"
  },

  // --- ORNAMENTAIS E ARBUSTOS ---
  {
    id: "poda_roseira",
    name: "Roseira de Jardim",
    emoji: "ðŸŒ¹",
    color: "#be123c",
    image_url: "./images/podas/roseira.jpg",
    category: "Ornamentais e Arbustos",
    when_months: [1, 2, 3],
    when_info: "Fim do inverno, apÃ³s as geadas mais fortes e antes das primeiras brotaÃ§Ãµes primaveris.",
    pruning_types: "Poda de rejuvenescimento rigorosa em taÃ§a aberta.",
    how: "Retirar toda a madeira morta, doente e os raminhos fracos. Deixar 3 a 5 hastes fortes e saudÃ¡veis cortadas a 3 ou 4 gemas do chÃ£o. Corte a 45 graus, 5 mm acima de uma gema apontada para fora.",
    tools: "Tesoura de poda afiada com lÃ¢minas desinfetadas e luvas de cabedal compridas anti-espinhos.",
    tips: "Corte sempre no sentido exterior para que os novos ramos cresÃ§am em forma de taÃ§a aberta, permitindo sol no centro e evitando fungos.",
    difficulty: "FÃ¡cil"
  },
  {
    id: "poda_hortensia",
    name: "HortÃªnsia",
    emoji: "ðŸª»",
    color: "#2563eb",
    image_url: "./images/podas/hortensia.jpg",
    category: "Ornamentais e Arbustos",
    when_months: [2, 3],
    when_info: "Final do inverno, quando o perigo de geadas severas jÃ¡ diminuiu.",
    pruning_types: "Limpeza de inflorescÃªncias secas e rejuvenescimento.",
    how: "Cortar as hastes com flores secas do ano anterior logo acima do primeiro par de gomos grossos e sadios. Remover ramos muito velhos ou entrelaÃ§ados na base para estimular novos rebentos vigorosos.",
    tools: "Tesoura de poda de mÃ£o.",
    tips: "NÃ£o corte ramos novos que nÃ£o deram flor no ano anterior: Ã© precisamente nesses ramos que surgirÃ£o as maiores flores deste ano.",
    difficulty: "FÃ¡cil"
  },
  {
    id: "poda_lavanda",
    name: "Alfazema (Lavanda)",
    emoji: "ðŸ’œ",
    color: "#8b5cf6",
    image_url: "./images/podas/lavanda.jpg",
    category: "Ornamentais e Arbustos",
    when_months: [8, 9],
    when_info: "Final do verÃ£o, apÃ³s a floraÃ§Ã£o secar, ou no final do inverno.",
    pruning_types: "Poda de conformaÃ§Ã£o arredondada em almofada.",
    how: "Aparar os caules florais secos e cerca de 2 a 3 cm do crescimento verde superior do arbusto, dando formato de meia-esfera.",
    tools: "Tesoura de poda ou tesoura de sebes bem afiada.",
    tips: "NUNCA corte fundo na madeira velha e lenhosa desprovida de folhas, pois a alfazema raramente volta a brotar de madeira velha e pode secar.",
    difficulty: "FÃ¡cil"
  }
];

export const DEFAULT_MONDAS = [
  // --- RAÃZES E TUBÃ‰RCULOS ---
  {
    id: "monda_cenoura",
    name: "Cenoura",
    emoji: "ðŸ¥•",
    color: "#ea580c",
    image_url: "./images/mondas/cenoura.jpg",
    category: "RaÃ­zes e TubÃ©rculos",
    when_months: [3, 4, 5, 6, 9, 10],
    when_stage: "Quando as pequenas plÃ¢ntulas atingirem 3 a 5 cm de altura e apresentarem 2 a 3 folhas verdadeiras recortadas.",
    spacing: "EspaÃ§amento final de 5 a 7 cm entre cenouras para raÃ­zes grossas e direitas sem deformaÃ§Ãµes.",
    how: "Regar o canteiro 1 hora antes para soltar a terra. Puxar as plÃ¢ntulas excedentÃ¡rias na vertical suavemente, segurando o solo com a outra mÃ£o para nÃ£o abalar as vizinhas.",
    tips: "A monda liberta Ã³leo essencial aromÃ¡tico que atrai a mosca-da-cenoura: realize a monda ao fim da tarde em dias frescos e comprima ligeiramente o solo Ã  volta das plantas que ficam."
  },
  {
    id: "monda_rabanete",
    name: "Rabanete",
    emoji: "ðŸŒ±",
    color: "#e11d48",
    image_url: "./images/mondas/rabanete.jpg",
    category: "RaÃ­zes e TubÃ©rculos",
    when_months: [3, 4, 5, 6, 9, 10],
    when_stage: "Cerca de 10 a 14 dias apÃ³s a germinaÃ§Ã£o rÃ¡pida da sementeira.",
    spacing: "3 a 5 cm de distÃ¢ncia entre rabanetes na linha.",
    how: "Desbastar os rebentos mais fracos e amontoados; manter os de folhagem mais baixa e caule mais aprumado.",
    tips: "Se nÃ£o forem mondados a tempo, os rabanetes espigam prematuramente e as raÃ­zes ficam finas, duras e amargas."
  },
  {
    id: "monda_beterraba",
    name: "Beterraba de Mesa",
    emoji: "ðŸŸ£",
    color: "#9d174d",
    image_url: "./images/mondas/beterraba.jpg",
    category: "RaÃ­zes e TubÃ©rculos",
    when_months: [3, 4, 5, 6, 7],
    when_stage: "Quando as folhas atingirem cerca de 5 a 8 cm de altura.",
    spacing: "10 a 12 cm de distÃ¢ncia entre raÃ­zes para formaÃ§Ã£o de bolbos redondos e generosos.",
    how: "Cada semente de beterraba Ã© na verdade um 'glomÃ©rulo' com 2 a 4 sementes: desbaste obrigatÃ³rio deixando apenas a plÃ¢ntula mais vigorosa de cada grupo.",
    tips: "As folhas jovens avermelhadas retiradas durante o desbaste sÃ£o extremamente ricas em ferro e deliciosas cruas em saladas ou cozinhadas como espinafre."
  },
  {
    id: "monda_nabo",
    name: "Nabo e NabiÃ§as",
    emoji: "ðŸ¥¬",
    color: "#65a30d",
    image_url: "./images/mondas/nabo.jpg",
    category: "RaÃ­zes e TubÃ©rculos",
    when_months: [8, 9, 10, 11],
    when_stage: "3 semanas apÃ³s a sementeira a lanÃ§o tÃ­pica do outono.",
    spacing: "10 a 15 cm de distÃ¢ncia para colheita de nabos grossos (ou 5 cm para colheita contÃ­nua de nabiÃ§as e grelos).",
    how: "Desbaste manual seletivo arrancando tufos densos.",
    tips: "Os rebentos retirados da monda sÃ£o as autÃªnticas nabiÃ§as tenras tradicionais para o caldo verde e sopas portuguesas."
  },

  // --- FOLHAS E SALADAS ---
  {
    id: "monda_alface",
    name: "Alface de Canteiro",
    emoji: "ðŸ¥¬",
    color: "#16a34a",
    image_url: "./images/mondas/alface.jpg",
    category: "Folhas e Saladas",
    when_months: [2, 3, 4, 5, 6, 9, 10],
    when_stage: "Quando as plÃ¢ntulas comeÃ§arem a sobrepor as primeiras folhinhas no canteiro.",
    spacing: "25 a 30 cm de compasso final para alfaces de repolho e 15 cm para alfaces de cortar.",
    how: "Desbastar as mais dÃ©beis ou estioladas. As plantas sadias arrancadas com raiz intacta podem ser imediatamente transplantadas (repicadas) para outro canteiro hÃºmido.",
    tips: "Nunca deixe as alfaces apertadas: o excesso de humidade entre folhas compactas favorece o mÃ­ldio e o ataque de caracÃ³is e lesmas."
  },
  {
    id: "monda_espinafre",
    name: "Espinafre Verdadeiro",
    emoji: "ðŸƒ",
    color: "#15803d",
    image_url: "./images/mondas/espinafre.jpg",
    category: "Folhas e Saladas",
    when_months: [2, 3, 4, 9, 10],
    when_stage: "Quando as mudas tiverem 4 folhas verdadeiras formadas.",
    spacing: "15 a 20 cm entre plantas na linha.",
    how: "Desbastar mantendo as plantas com rosetas basais mais largas e verdes.",
    tips: "O espinafre nÃ£o suporta calor forte nem falta de espaÃ§o, tendendo a espigar. A monda atempada atrasa a subida a flor e prolonga a colheita de folhas tenras."
  },
  {
    id: "monda_rucula",
    name: "RÃºcula",
    emoji: "ðŸ¥—",
    color: "#16a34a",
    image_url: "./images/mondas/rucula.jpg",
    category: "Folhas e Saladas",
    when_months: [3, 4, 5, 9, 10],
    when_stage: "10 a 15 dias apÃ³s a sementeira.",
    spacing: "8 a 10 cm entre pÃ©s para formar touÃ§as folhosas.",
    how: "Arranque cuidadoso com as pontas dos dedos das plantas excessivas.",
    tips: "Aproveite a monda como microvegetais (microgreens) gourmet picantes para temperar queijos, tostas e saladas."
  },
  {
    id: "monda_acelga",
    name: "Acelga de Penacho",
    emoji: "ðŸŒ±",
    color: "#b91c1c",
    image_url: "./images/mondas/acelga.jpg",
    category: "Folhas e Saladas",
    when_months: [3, 4, 5, 6],
    when_stage: "Quando as mudas medirem cerca de 6 a 8 cm de altura.",
    spacing: "25 a 35 cm entre plantas para permitir o desenvolvimento de grandes pencas e talos carnudos.",
    how: "Eliminar pÃ©s fracos e deixar os exemplares com talos mais grossos e eretos.",
    tips: "As acelgas produzem folhas continuamente durante meses se for colhendo as folhas exteriores Ã  medida que crescem."
  },

  // --- ALLIUM ---
  {
    id: "monda_alho",
    name: "Alho",
    emoji: "ðŸ§„",
    color: "#a16207",
    image_url: "./images/mondas/alho.jpg",
    category: "Allium",
    when_months: [1, 2, 3, 4, 11, 12],
    when_stage: "Logo no inÃ­cio do surgimento de infestantes apÃ³s a brotaÃ§Ã£o dos dentes de alho.",
    spacing: "10 a 15 cm entre dentes na linha e 25 cm entre linhas.",
    how: "Monda manual constante com sacho fino e leve. As raÃ­zes do alho sÃ£o superficiais e fracas competidoras contra ervas espontÃ¢neas.",
    tips: "Mantenha o canteiro 100% limpo de ervas daninhas nos primeiros 3 meses para garantir cabeÃ§as de alho grandes e densas."
  },
  {
    id: "monda_alho_porro",
    name: "Alho-francÃªs (Alho-porro)",
    emoji: "ðŸ¥¢",
    color: "#059669",
    image_url: "./images/mondas/alho_porro.jpg",
    category: "Allium",
    when_months: [3, 4, 5, 6],
    when_stage: "Em alfobre (quando as mudas tiverem a grossura de uma agulha) ou apÃ³s o transplante.",
    spacing: "15 cm entre plantas na linha e 30 cm entre linhas.",
    how: "Desbastar mudas frÃ¡geis. No transplante para o local definitivo, aparar ligeiramente as raÃ­zes e as pontas das folhas para estimular o enraizamento.",
    tips: "FaÃ§a amontoa gradual (aconchegar terra ao pÃ© do talo) para branquear a haste e tornÃ¡-la tenra e doce."
  },
  {
    id: "monda_cebola",
    name: "Cebola",
    emoji: "ðŸ§…",
    color: "#d97706",
    image_url: "./images/mondas/cebola.jpg",
    category: "Allium",
    when_months: [1, 2, 3, 4],
    when_stage: "Quando os caules tiverem 10 a 12 cm de altura em alfobre antes do transplante ou sementeira direta.",
    spacing: "12 a 15 cm entre bolbos para permitir o engrossamento uniforme da cebola.",
    how: "Remover pÃ©s finos e amontoados. NÃ£o enterrar demasiado o bolbo no solo; o bolbo deve desenvolver-se praticamente Ã  superfÃ­cie.",
    tips: "Evite adubos ricos em azoto apÃ³s a formaÃ§Ã£o do bolbo para nÃ£o apodrecer a cebola na cura."
  },

  // --- SOLANÃCEAS ---
  {
    id: "monda_tomateiro",
    name: "Tomateiro (Desladroamento e Monda)",
    emoji: "ðŸ…",
    color: "#dc2626",
    image_url: "./images/mondas/tomateiro.jpg",
    category: "SolanÃ¡ceas",
    when_months: [5, 6, 7, 8],
    when_stage: "Durante todo o crescimento ativo do tomateiro tutorado (todas as semanas).",
    spacing: "Manter apenas 1 haste principal (ou 2 no mÃ¡ximo) por tutor ou estaca.",
    how: "Retirar com os dedos os rebentos axilares ('ladrÃµes') que nascem na junÃ§Ã£o das folhas com o caule principal logo que atinjam 2 a 4 cm. Mais tarde, fazer a monda de frutos retirando tomates minÃºsculos mal formados no cacho.",
    tips: "FaÃ§a o desladroamento em dias quentes e ensolarados para que a pequena ferida cicatrize em minutos, impedindo a entrada de esporos de mÃ­ldio."
  },
  {
    id: "monda_pimenteiro",
    name: "Pimenteiro (Pimentos e Malaguetas)",
    emoji: "ðŸ«‘",
    color: "#16a34a",
    image_url: "./images/mondas/pimenteiro.jpg",
    category: "SolanÃ¡ceas",
    when_months: [5, 6, 7],
    when_stage: "Logo no inÃ­cio da ramificaÃ§Ã£o em 'Y' da planta.",
    spacing: "40 a 50 cm de distÃ¢ncia entre plantas na horta.",
    how: "Retirar a 'flor-rei' (a primeira flor solitÃ¡ria que nasce no meio da primeira bifurcaÃ§Ã£o em Y) para a planta crescer com mais vigor e produzir dezenas de pimentos laterais em vez de apenas um fruto inicial gigante.",
    tips: "Desbastar os rebentos baixos abaixo da primeira ramificaÃ§Ã£o para arejar a base e evitar podridÃ£o das folhas."
  },
  {
    id: "monda_beringela",
    name: "Beringela",
    emoji: "ðŸ†",
    color: "#7c2d12",
    image_url: "./images/mondas/beringela.jpg",
    category: "SolanÃ¡ceas",
    when_months: [5, 6, 7],
    when_stage: "Durante o vingamento das primeiras flores e frutos.",
    spacing: "50 a 60 cm entre plantas.",
    how: "Limpar rebentos axilares baixos. Deixar 4 a 6 frutos bem formados por planta e retirar os frutos excedentes tardios para garantir beringelas grandes e brilhantes.",
    tips: "A beringela necessita de muito sol e calor constante no pÃ©; cubra o solo com palha para reter calor e humidade."
  },

  // --- CUCURBITÃCEAS ---
  {
    id: "monda_curgete",
    name: "Curgete",
    emoji: "ðŸ¥’",
    color: "#15803d",
    image_url: "./images/mondas/curgete.jpg",
    category: "CucurbitÃ¡ceas",
    when_months: [4, 5, 6],
    when_stage: "Sementeira em cova: quando germinarem 3 a 4 plantinhas com as primeiras folhas.",
    spacing: "Deixar apenas 1 planta (a mais robusta) por cova, com 80 a 100 cm de distÃ¢ncia entre covas.",
    how: "Cortar com tesoura rente ao chÃ£o as plantas excedentes em vez de arrancar pelas raÃ­zes, pois as cucurbitÃ¡ceas tÃªm raÃ­zes frÃ¡geis que se danificam facilmente.",
    tips: "Colher as curgetes com 15 a 20 cm: quanto mais curgetes colher, mais flores fÃªmeas a planta continuarÃ¡ a produzir sem descanso."
  },
  {
    id: "monda_abobora",
    name: "AbÃ³bora",
    emoji: "ðŸŽƒ",
    color: "#f59e0b",
    image_url: "./images/mondas/abobora.jpg",
    category: "CucurbitÃ¡ceas",
    when_months: [4, 5, 6],
    when_stage: "ApÃ³s o nascimento das plÃ¢ntulas na cova e mais tarde durante o vingamento dos frutos.",
    spacing: "Deixar 1 a 2 plantas por cova (espaÃ§adas de 1.5 a 2 metros).",
    how: "Na fase inicial, desbaste de plantas. Na fase adulta (monda de frutos), desponte as guias apÃ³s 2 a 3 abÃ³boras vingadas para que a planta canalize todo o aÃ§Ãºcar para esses frutos.",
    tips: "Coloque uma telha, tÃ¡bua ou palha seca debaixo de cada fruto no chÃ£o para que a humidade da terra nÃ£o apodreÃ§a a casca."
  },
  {
    id: "monda_melao",
    name: "MelÃ£o e Melancia",
    emoji: "ðŸˆ",
    color: "#ca8a04",
    image_url: "./images/mondas/melao.jpg",
    category: "CucurbitÃ¡ceas",
    when_months: [4, 5, 6],
    when_stage: "Quando as guias comeÃ§arem a ramificar e formarem os primeiros frutos do tamanho de uma noz.",
    spacing: "Deixar apenas 2 a 3 melÃµes por planta.",
    how: "Despontar a guia principal acima da 4Âª ou 5Âª folha para forÃ§ar ramos laterais florÃ­feros. Fazer a monda de frutos eliminando os mais pequenos ou disformes.",
    tips: "Menos frutos por planta significa frutos muito mais doces, aromÃ¡ticos e sumarentos."
  },

  // --- CEREAIS E LEGUMINOSAS ---
  {
    id: "monda_milho",
    name: "Milho Doce e GrÃ£o",
    emoji: "ðŸŒ½",
    color: "#eab308",
    image_url: "./images/mondas/milho.jpg",
    category: "Cereais",
    when_months: [4, 5, 6],
    when_stage: "Quando o milho atingir cerca de 10 a 15 cm de altura (o tamanho de um palmo).",
    spacing: "20 a 25 cm entre plantas na linha e 70 a 80 cm entre linhas.",
    how: "Deixar apenas 1 pÃ© forte por golpe. Eliminar afilhos ou ladrÃµes secundÃ¡rios na base do colmo para concentrar energia na espiga principal.",
    tips: "O milho Ã© polinizado pelo vento: plante sempre em blocos de 3 a 4 linhas paralelas curtas em vez de uma Ãºnica linha comprida para garantir espigas cheias de grÃ£os."
  },
  {
    id: "monda_favas",
    name: "Favas e Ervilhas",
    emoji: "ðŸ«›",
    color: "#15803d",
    image_url: "./images/mondas/favas.jpg",
    category: "Leguminosas",
    when_months: [10, 11, 12, 1],
    when_stage: "Quando as favas tiverem cerca de 10 cm de altura e mais tarde na desponta de primavera.",
    spacing: "15 a 20 cm entre plantas e 40 a 50 cm entre linhas.",
    how: "Monda manual das ervas daninhas de inverno. Na primavera, despontar o topo apical da fava (remover os Ãºltimos 5 a 10 cm) apÃ³s o aparecimento de 5 a 6 andares de vagens.",
    tips: "Despontar o topo da fava elimina o poiso preferido do piolho-negro (pulgÃ£o) e concentra a seiva nas vagens inferiores, que engordam rapidamente."
  },

  // --- BRÃSSICAS ---
  {
    id: "monda_couve",
    name: "Couves e Repolhos",
    emoji: "ðŸ¥¦",
    color: "#047857",
    image_url: "./images/mondas/couve.jpg",
    category: "BrÃ¡ssicas",
    when_months: [6, 7, 8, 9, 10],
    when_stage: "Em alfobre (desbaste para nÃ£o estiolarem) e na horta apÃ³s o enraizamento.",
    spacing: "40 a 60 cm de distÃ¢ncia no transplante final.",
    how: "Selecionar no alfobre apenas as mudas de pÃ© grosso, caule firme e sem nÃ³s na raiz. Na horta, sachar o canteiro eliminando infestantes.",
    tips: "FaÃ§a amontoa aconchegando terra hÃºmida ao redor do caule principal para dar estabilidade contra ventos fortes de outono e estimular novas raÃ­zes adventÃ­cias."
  },

  // --- ERVAS AROMÃTICAS ---
  {
    id: "monda_salsa",
    name: "Salsa e Coentros",
    emoji: "ðŸŒ¿",
    color: "#10b981",
    image_url: "./images/mondas/salsa.jpg",
    category: "Ervas AromÃ¡ticas",
    when_months: [3, 4, 5, 6, 9, 10],
    when_stage: "Quando as sementeiras densas formarem pequenos tufos de 4 a 6 cm de altura.",
    spacing: "10 a 15 cm entre tufos.",
    how: "Arranque manual com cuidado dos pÃ©s em excesso.",
    tips: "Os pÃ©s retirados jÃ¡ tÃªm aroma concentrado e devem ser usados imediatamente na cozinha para temperar peixes, caldeiradas ou saladas."
  },
  {
    id: "monda_manjericao",
    name: "ManjericÃ£o",
    emoji: "ðŸŒ±",
    color: "#059669",
    image_url: "./images/mondas/manjericao.jpg",
    category: "Ervas AromÃ¡ticas",
    when_months: [4, 5, 6, 7],
    when_stage: "Quando o manjericÃ£o tiver 4 a 5 pares de folhas verdadeiras.",
    spacing: "20 a 25 cm entre plantas para permitir o desenvolvimento de um arbusto denso.",
    how: "Desbaste de mudas fracas. Fazer o beliscÃ£o (desponta do topo central) para quebrar a dominÃ¢ncia apical e forÃ§ar o crescimento de ramos laterais.",
    tips: "Corte imediatamente qualquer botÃ£o floral que comece a despontar: a floraÃ§Ã£o torna as folhas de manjericÃ£o amargas e interrompe o crescimento de folhagem nova."
  }
];

