import React from 'react';
import { Palette, Check } from 'lucide-react';
import { THEMES } from '@/lib/appearance';
import { regionalMessage } from '@/lib/regionalMessages';
export default function AppearanceFields({ value, onChange, language }) {
  const t = key => regionalMessage(key,language);
  const patch = data => onChange({ ...value, ...data });
  return <section className="space-y-5 p-1 sm:p-2"><div><h2 className="flex items-center gap-2 text-xl font-bold text-stone-800"><Palette className="h-5 w-5 text-emerald-700" />{t('appearance')}</h2><p className="mt-2 text-sm leading-relaxed text-stone-500">{t('appearanceIntro')}</p></div>
    <fieldset><legend className="mb-3 text-xs font-bold uppercase tracking-wide text-stone-600">{t('palette')}</legend><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(THEMES).map(([key,colors])=><button key={key} type="button" aria-pressed={value.theme===key} onClick={()=>patch({theme:key})} className={`overflow-hidden rounded-2xl border-2 text-left ${value.theme===key?'border-stone-700':'border-stone-100'}`}><span className="flex h-16 items-end justify-end p-2" style={{background:`linear-gradient(135deg,#${colors[4]},#${colors[8]})`}}>{value.theme===key&&<Check className="h-5 w-5 text-white" />}</span><span className="block bg-white p-2.5 text-xs font-bold text-stone-700">{t(key)}</span></button>)}</div></fieldset>
    <fieldset><legend className="mb-3 text-xs font-bold uppercase tracking-wide text-stone-600">{t('texture')}</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{['none','paper','dots','leaves'].map(key=><button key={key} type="button" aria-pressed={value.texture===key} onClick={()=>patch({texture:key})} className={`rounded-xl border px-3 py-3 text-xs font-semibold ${value.texture===key?'border-emerald-600 bg-emerald-50 text-emerald-900':'border-stone-200 text-stone-600'}`}>{t(key)}</button>)}</div></fieldset>
    <div className="space-y-3 rounded-2xl bg-stone-50 p-4">{[['fontSize','largeText',value.fontSize==='large'],['reduceMotion','reducedMotion',value.reduceMotion],['highContrast','highContrast',value.highContrast]].map(([key,label,checked])=><label key={key} className="flex items-center justify-between gap-3 text-sm font-semibold text-stone-700">{t(label)}<input type="checkbox" className="h-5 w-5 accent-emerald-700" checked={checked} onChange={event=>patch({[key]:key==='fontSize'?(event.target.checked?'large':'normal'):event.target.checked})} /></label>)}</div>
    <div className="overflow-hidden rounded-2xl border border-stone-100 p-5" style={{background:`#${THEMES[value.theme][0]}`}}><span className="text-3xl">🌱</span><h3 className="mt-2 text-lg font-bold" style={{color:`#${THEMES[value.theme][9]}`}}>{t('yourGarden')}</h3><p className="mt-1 text-sm text-stone-600">{t('appearancePreview')}</p><span className="mt-4 inline-flex rounded-xl px-4 py-2 text-sm font-bold text-white" style={{background:`#${THEMES[value.theme][7]}`}}>{t('start')}</span></div>
  </section>;
}
